import { RaurusClientProvider } from "@raurus/react/client";
import type { Metadata } from "next";

import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { FC, PropsWithChildren } from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = PropsWithChildren;

const Layout: FC<Props> = ({ children }) => {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <RaurusClientProvider url="http://localhost:3000">{children}</RaurusClientProvider>
            </body>
        </html>
    );
};

export default Layout;
